const grains = [
    { id: "1", name: "Rice" },
    { id: "2", name: "Quinoa" },
    { id: "3", name: "Oats" },
    { id: "4", name: "Barley" },
    { id: "5", name: "Wheat" },
    { id: "6", name: "Cornmeal" },
    { id: "7", name: "Couscous" },
    { id: "8", name: "Buckwheat" },
    { id: "9", name: "Millet" },
    { id: "10", name: "Farro" },
    { id: "11", name: "Amaranth" },
    { id: "12", name: "Bulgur" },
    { id: "13", name: "Polenta" },
    { id: "14", name: "Wild rice" },
    { id: "15", name: "Spelt" },
    { id: "16", name: "Rye" },
    { id: "17", name: "Cereal grains (e.g., barley, wheat, oats)" },
    { id: "18", name: "Couscous" },
    { id: "19", name: "Masa harina" },
    { id: "20", name: "Sorghum" },
    { id: "21", name: "Triticale" },
    { id: "22", name: "Cornmeal" },
    { id: "23", name: "Polenta" },
    { id: "24", name: "Cornflour" },
    { id: "25", name: "Semolina" },
    { id: "26", name: "Rice flour" },
    { id: "27", name: "Bread flour" },
    { id: "28", name: "Pastry flour" },
    { id: "29", name: "Cake flour" },
    { id: "30", name: "Whole wheat flour" },
  ];
  
  export default grains;