const meats = [
    { id: "1", name: "Chicken" },
    { id: "2", name: "Beef" },
    { id: "3", name: "Pork" },
    { id: "4", name: "Lamb" },
    { id: "5", name: "Turkey" },
    { id: "6", name: "Fish (e.g., salmon, cod, tilapia)" },
    { id: "7", name: "Shrimp" },
    { id: "8", name: "Crab" },
    { id: "9", name: "Lobster" },
    { id: "10", name: "Bacon" },
    { id: "11", name: "Sausage" },
    { id: "12", name: "Ground beef" },
    { id: "13", name: "Steak" },
    { id: "14", name: "Pork chops" },
    { id: "15", name: "Ground turkey" },
    { id: "16", name: "Ham" },
    { id: "17", name: "Veal" },
    { id: "18", name: "Duck" },
    { id: "19", name: "Venison" },
    { id: "20", name: "Chicken thighs" },
    { id: "21", name: "Chicken breasts" },
    { id: "22", name: "Ground chicken" },
    { id: "23", name: "Ground pork" },
    { id: "24", name: "Salami" },
    { id: "25", name: "Pastrami" },
    { id: "26", name: "Pepperoni" },
    { id: "27", name: "Sliced turkey" },
    { id: "28", name: "Roast beef" },
    { id: "29", name: "Lamb chops" },
    { id: "30", name: "Sliced ham" },
  ];
  
  export default meats;