const seasonings = [
    { id: "1", name: "Salt" },
    { id: "2", name: "Black pepper" },
    { id: "3", name: "Garlic powder" },
    { id: "4", name: "Onion powder" },
    { id: "5", name: "Chili powder" },
    { id: "6", name: "Paprika" },
    { id: "7", name: "Cayenne pepper" },
    { id: "8", name: "Oregano" },
    { id: "9", name: "Basil" },
    { id: "10", name: "Thyme" },
    { id: "11", name: "Rosemary" },
    { id: "12", name: "Cumin" },
    { id: "13", name: "Coriander" },
    { id: "14", name: "Cinnamon" },
    { id: "15", name: "Nutmeg" },
    { id: "16", name: "Ginger" },
    { id: "17", name: "Turmeric" },
    { id: "18", name: "Curry powder" },
    { id: "19", name: "Dried parsley" },
    { id: "20", name: "Dill" },
    { id: "21", name: "Bay leaves" },
    { id: "22", name: "Celery salt" },
    { id: "23", name: "Mustard powder" },
    { id: "24", name: "Fennel seeds" },
    { id: "25", name: "Smoked paprika" },
    { id: "26", name: "Herbs de Provence" },
    { id: "27", name: "Allspice" },
    { id: "28", name: "Cloves" },
    { id: "29", name: "Cardamom" },
    { id: "30", name: "Sage" },
  ];
  
  export default seasonings;