const vegetables = [
    { id: "1", name: "Carrot" },
    { id: "2", name: "Broccoli" },
    { id: "3", name: "Cauliflower" },
    { id: "4", name: "Spinach" },
    { id: "5", name: "Kale" },
    { id: "6", name: "Zucchini" },
    { id: "7", name: "Eggplant" },
    { id: "8", name: "Bell pepper" },
    { id: "9", name: "Tomato" },
    { id: "10", name: "Cucumber" },
    { id: "11", name: "Mushroom" },
    { id: "12", name: "Onion" },
    { id: "13", name: "Garlic" },
    { id: "14", name: "Ginger" },
    { id: "15", name: "Potato" },
    { id: "16", name: "Sweet potato" },
    { id: "17", name: "Corn" },
    { id: "18", name: "Peas" },
    { id: "19", name: "Green beans" },
    { id: "20", name: "Asparagus" },
    { id: "21", name: "Brussels sprouts" },
    { id: "22", name: "Cabbage" },
    { id: "23", name: "Celery" },
    { id: "24", name: "Leek" },
    { id: "25", name: "Lettuce" },
    { id: "26", name: "Radish" },
    { id: "27", name: "Pumpkin" },
    { id: "28", name: "Artichoke" },
    { id: "29", name: "Beetroot" },
    { id: "30", name: "Celeriac" },
  ];
  
  export default vegetables;